version: '3.9'

services:
  task-app:
    build:
      context: .
      dockerfile: dev.dockerfile
    command: npm run start:dev
    environment:
      PORT: 3000
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
